import {
  Activity,
  BarChart3,
  Bell,
  ClipboardList,
  Dumbbell,
  Flame,
  Gauge,
  LayoutDashboard,
  List,
  Menu,
  Moon,
  RefreshCw,
  Settings,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  activity: Activity,
  moon: Moon,
  flame: Flame,
  dumbbell: Dumbbell,
  "bar-chart-3": BarChart3,
  sparkles: Sparkles,
  list: List,
  "clipboard-list": ClipboardList,
  settings: Settings,
  "refresh-cw": RefreshCw,
  bell: Bell,
  menu: Menu,
  gauge: Gauge,
};
